create table category
(
    id          bigint generated by default as identity,
    description varchar(255),
    name        varchar(255),
    primary key (id)
);
create table order_item
(
    id         bigint generated by default as identity,
    price      float(53),
    quantity   integer,
    order_id   bigint,
    product_id bigint,
    primary key (id)
);
create table orders
(
    total_amount float(53),
    id           bigint generated by default as identity,
    order_date   timestamp(6),
    user_id      bigint,
    primary key (id)
) ;
create table product
(
    price       float(53),
    category_id bigint,
    id          bigint generated by default as identity,
    description varchar(255),
    name        varchar(255),
    primary key (id)
) ;
create table users
(
    id       bigint generated by default as identity,
    mail     varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
) ;
